### ISSUE TITLE
lake of installation guidelines 

### ISSUE THREAD

**Issue by GuillermoAndrade** [deep-js/DeepJS#5]
Hello,
Maybe sometime is missing the reedme.md. I try to build using ubuntu 18.04 and node v10.15.1

After cloning the project and cd into, I have: 

```
~/program/DeepJS$ ng build
Could not find module "@angular-devkit/build-angular" from "/home/andradgu/program/DeepJS".
Error: Could not find module "@angular-devkit/build-angular" from "/home/andradgu/program/DeepJS".
    at Object.resolve (/usr/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (/usr/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js:132:40)
    at Observable._trySubscribe (/usr/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/usr/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:30:22)
    at /usr/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:99:19
    at new Promise (<anonymous>)
    at Observable.toPromise (/usr/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:97:16)
    at BuildCommand.initialize (/usr/lib/node_modules/@angular/cli/models/architect-command.js:91:94)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
```

**Comment by GuillermoAndrade** [comment]
it seem you need to run `npm install --save-dev @angular-devkit/build-angular` to install à missing dep.
